FROM mcr.microsoft.com/dotnet/sdk:6.0
COPY ./multipleprojects.sln /src/multipleprojects.sln
COPY ./web/myWebapp.csproj  /src/web/myWebapp.csproj
COPY ./projectone/projectone.csproj  /src/projectone/projectone.csproj
COPY ./projecttwo/projecttwo.csproj  /src/projecttwo/projecttwo.csproj

WORKDIR /src
RUN dotnet restore multipleprojects.sln

COPY . .

RUN dotnet build web/myWebApp.csproj -o /app
RUN dotnet publish web/myWebApp.csproj -o /publish
WORKDIR /app
EXPOSE 80
CMD ["./myWebApp"]
